import os
import smtplib
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

logger = logging.getLogger(__name__)

SMTP_HOST = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER = os.getenv("SMTP_USER", "")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "")
FROM_EMAIL = os.getenv("FROM_EMAIL", SMTP_USER)


async def send_email(to_email: str, summary: str, filename: str) -> None:
    """Send AI-generated summary to the specified email address."""
    if not SMTP_USER or not SMTP_PASSWORD:
        raise RuntimeError(
            "SMTP credentials not configured. Set SMTP_USER and SMTP_PASSWORD in your .env file."
        )

    subject = f"Sales Insight Report - {filename}"

    paragraphs = [p.strip() for p in summary.split('\n\n') if p.strip()]
    build_paragraphs = lambda s: ''.join(
        '<p style="margin: 0 0 16px 0;">' + p + '</p>' for p in paragraphs
    )

    html_body = f"""
    <html>
    <body style="font-family: Georgia, serif; max-width: 680px; margin: 0 auto; padding: 32px; color: #1a1a1a; background: #fafafa;">
      <div style="border-left: 4px solid #0a0a0a; padding-left: 24px; margin-bottom: 32px;">
        <h1 style="font-size: 22px; font-weight: 700; margin: 0 0 4px 0; letter-spacing: -0.5px;">Sales Insight Report</h1>
        <p style="margin: 0; color: #666; font-size: 14px;">Generated from: <strong>{filename}</strong></p>
      </div>
      <div style="line-height: 1.8; font-size: 15px; color: #333;">
        {build_paragraphs(summary)}
      </div>
      <hr style="border: none; border-top: 1px solid #e0e0e0; margin: 32px 0;" />
      <p style="font-size: 12px; color: #999; margin: 0;">
        This report was auto-generated by the <strong>Sales Insight Automator</strong> — Rabbitt AI internal tool.
      </p>
    </body>
    </html>
    """

    text_body = f"Sales Insight Report\nFile: {filename}\n\n{summary}"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = FROM_EMAIL
    msg["To"] = to_email
    msg.attach(MIMEText(text_body, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    logger.info(f"Sending email to {to_email} via {SMTP_HOST}:{SMTP_PORT}")

    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
        server.ehlo()
        server.starttls()
        server.login(SMTP_USER, SMTP_PASSWORD)
        server.sendmail(FROM_EMAIL, to_email, msg.as_string())

    logger.info(f"Email sent successfully to {to_email}")
